[package]
name = "horde"
description = "Rust binary analysis and reverse engineering framework with Python bindings"
version = "0.1.0"

edition = "2021"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/standard3/horde/"

[dependencies]
anyhow = "1.0.86"
goblin = "0.8.2"
